name: dart_strapi
description: http client for strapi, you can access your models by name or the custom ones using the http client.
version: 0.0.3
homepage: https://github.com/xantiagoma/dart_strapi

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.8

dev_dependencies:
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
  pedantic: ^1.8.0
  test: ^1.6.0
