name: dart_strapi_client
description: dart client for Strapi V5
version: 0.0.1
homepage: https://github.com/mechtee/dart_strapi

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  tuple: ^2.0.2

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  test: ^1.25.8
